<?php
// $Id$

function openaustralia_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#openaustralia":
      $output = '<p>'. t("Shows you recent speeches by your MP from OpenAustralia.org.") .'</p>';
      break;
  }
  return $output;
}

function openaustralia_permission() {
  return array(
    'view OpenAustralia speeches' => array(
      'title' => t('View OpenAustralia speeches')
    )
  );
}

function openaustralia_block_info() {
  $blocks['recent_speeches'] = array(
    'info' => t('OpenAustralia'),
  );
  return $blocks;
}

function openaustralia_block_view($delta = '') {
  switch ($delta) {
    case 'recent_speeches':
      $block['subject'] = t('My MPs recent speeches');

      $xml = simplexml_load_file("http://www.openaustralia.org/api/getHansard?key=FMzR8pDUrEebHCuLT4AKJYC6&output=xml&person=10513");

      // Get some information about the MP
      $MPname = (string) $xml->rows->match->speaker->first_name . ' ' . $xml->rows->match->speaker->last_name;
      $MPconstituency = (string) $xml->rows->match->speaker->constituency;
      $MPurl = (string) $xml->rows->match->speaker->url;

      // Display the MP name and constituency
      $block_content = '<a href="http://www.openaustralia.org'.$MPurl.'">'.$MPname.', MP - Member for '.$MPconstituency.'</a>';

      $block_content .= '<ul>';
      $i = 0; //counter for number of meetings
      foreach ($xml->rows->match as $match){
          if ($i >= 5) { break; } // don't list more than 5 meetings
          $date = strtotime($match->hdate);
          $block_content .=  '<li><b>';
          $block_content .=  date('j M', $date) . ': ';
          $block_content .= '<a href="http://www.openaustralia.org' . $match->listurl . '">' . $match->parent->body . '</a></b>';
          $block_content .= '<br/>' . $match->body;
          $block_content .= '</li>'."\n";
          $i++; //increment the counter
      }
      $block_content .= '</ul>';
      $block_content .= '<p>More from <a href="http://www.openaustralia.org' . $MPurl . '">OpenAustralia.org</a></p>';

      $block['content'] = $block_content;
      break;
  }
  return $block;
}
