<?php
// $Id$

function openaustralia_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#openaustralia":
      $output = '<p>'. t("Shows you recent speeches by your MP from OpenAustralia.org.") .'</p>';
      break;
  }
  return $output;
}

function openaustralia_permission() {
  return array(
    'view OpenAustralia speeches' => array(
      'title' => t('View OpenAustralia speeches')
    )
  );
}
